/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-12 23:56:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.review;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reviewform2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/for%20studying/spring_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668700713831L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<title>Jimat - Food choice for you</title>\r\n");
      out.write("<link href=\"/css/review.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\"\r\n");
      out.write("	crossorigin=\"anonymous\" />\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/edd4d6d779.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(\r\n");
      out.write("			function() {\r\n");
      out.write("				$('#comment-send').click(\r\n");
      out.write("						function() {\r\n");
      out.write("							$('[name=review_content]').val(\r\n");
      out.write("									$('[name=review_content]').val().replace(\r\n");
      out.write("											/\\n/gi, '<br>'));\r\n");
      out.write("							$('#frm').attr('action', 'review_update.do')\r\n");
      out.write("									.submit();\r\n");
      out.write("						});\r\n");
      out.write("			});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		<form id=\"frm\" method=\"post\">\r\n");
      out.write("			<div class=\"card p-3 col-lg-9 mt-3\" id=\"comment-body\">\r\n");
      out.write("				<div class=\"comment-box-body column-row p-3\">\r\n");
      out.write("					<div class=\"comment-box column-row mb-4 column-row\">\r\n");
      out.write("						<div class=\"row\" id=\"row1\">\r\n");
      out.write("							<div class=\"comment-rating d-flex justify-content-between p-0\">\r\n");
      out.write("								<div class=\"title m-0 p-0\">\r\n");
      out.write("									<p>\r\n");
      out.write("									<h4>리뷰 작성하기</h4>\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"rating flex-row-reverse ms-3\">\r\n");
      out.write("									<input type=\"radio\" name=\"rating\" value=\"1\" id=\"1\" /> <label\r\n");
      out.write("										id=\"stars\" for=\"1\">☆</label> <input type=\"radio\" name=\"rating\"\r\n");
      out.write("										value=\"2\" id=\"2\" /> <label id=\"stars\" for=\"2\">☆</label> <input\r\n");
      out.write("										type=\"radio\" name=\"rating\" value=\"3\" id=\"3\" /> <label\r\n");
      out.write("										id=\"stars\" for=\"3\">☆</label> <input type=\"radio\" name=\"rating\"\r\n");
      out.write("										value=\"4\" id=\"4\" /> <label id=\"stars\" for=\"4\">☆</label> <input\r\n");
      out.write("										type=\"radio\" name=\"rating\" value=\"5\" id=\"5\" /> <label\r\n");
      out.write("										id=\"stars\" for=\"5\">☆</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"comment-tag\">\r\n");
      out.write("									<div class=\"btn-group\" role=\"group\"\r\n");
      out.write("										aria-label=\"Basic radio toggle button group\">\r\n");
      out.write("										<input type=\"checkbox\" class=\"btn-check\" name=\"btnradio\"\r\n");
      out.write("											id=\"taste\" autocomplete=\"off\" /> <label\r\n");
      out.write("											class=\"btn btn-outline-danger\" for=\"taste\">#맛</label> <input\r\n");
      out.write("											type=\"checkbox\" class=\"btn-check\" name=\"btnradio\" id=\"price\"\r\n");
      out.write("											autocomplete=\"off\" /> <label class=\"btn btn-outline-warning\"\r\n");
      out.write("											for=\"price\">#가격</label> <input type=\"checkbox\"\r\n");
      out.write("											class=\"btn-check\" name=\"btnradio\" id=\"service\"\r\n");
      out.write("											autocomplete=\"off\" /> <label class=\"btn btn-outline-info\"\r\n");
      out.write("											for=\"service\">#서비스</label> <input type=\"checkbox\"\r\n");
      out.write("											class=\"btn-check\" name=\"btnradio\" id=\"mood\"\r\n");
      out.write("											autocomplete=\"off\" /> <label class=\"btn btn-outline-primary\"\r\n");
      out.write("											for=\"mood\">#분위기</label> <input type=\"checkbox\"\r\n");
      out.write("											class=\"btn-check\" name=\"btnradio\" id=\"parking\"\r\n");
      out.write("											autocomplete=\"off\" /> <label class=\"btn btn-outline-success\"\r\n");
      out.write("											for=\"parking\">#주차</label>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row\" id=\"row2\">\r\n");
      out.write("						<div class=\"comment-area p-0\">\r\n");
      out.write("							<textarea class=\"form-control\" name=\"review_content\"\r\n");
      out.write("								rows=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review_dto.review_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row\" id=\"row3\">\r\n");
      out.write("						<div class=\"write-buttons mt-3 d-flex justify-content-center\">\r\n");
      out.write("							<input class=\"form-control\" type=\"file\" id=\"formFile\">\r\n");
      out.write("							<button class=\"btn btn-primary\" id=\"comment-send\">수정완료</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<input type=\"text\" name=\"review_writer_id\"\r\n");
      out.write("				value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review_dto.review_writer_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden=hidden> <input\r\n");
      out.write("				type=\"text\" name=\"review_seq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review_dto.review_seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("				hidden=hidden> <input type=\"text\"\r\n");
      out.write("				name=\"review_foodstore_seq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review_dto.review_foodstore_seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("				hidden=hidden> \r\n");
      out.write("		</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/review/reviewform2.jsp(34,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("review_dto");
      // /WEB-INF/views/review/reviewform2.jsp(34,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/review/reviewform2.jsp(34,1) '${review_dto}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${review_dto}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
