/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-19 09:10:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mainPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class oneKmMap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668700713831L));
    _jspx_dependants.put("jar:file:/C:/for%20studying/spring_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project_test/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<title>Jimat - Food choice for you</title>\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\"\n");
      out.write("	crossorigin=\"anonymous\" />\n");
      out.write("<script src=\"https://kit.fontawesome.com/edd4d6d779.js\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main.css\" type=\"text/css\"\n");
      out.write("	rel=\"stylesheet\" />\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/oneKmMap.js\"></script>\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("	src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=952441bca7c2877c20d98599bb8b06bd&amp;libraries=LIBRARY\"></script>\n");
      out.write("<script charset=\"UTF-8\"\n");
      out.write("	src=\"https://t1.daumcdn.net/mapjsapi/js/main/4.4.8/kakao.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"body-wrap container col-12 column-row\">\n");
      out.write("		<div class=\"row\">\n");
      out.write("			");
      out.write("\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/mainPage/mainMenu.jsp", out, false);
      out.write("\n");
      out.write("		</div>\n");
      out.write("		");
      out.write("\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"main container col-12 column-row mt-2 ms-3\">\n");
      out.write("				<div class=\"main-body containercol-md-12 d-flex\">\n");
      out.write("					<div class=\"main-menu col-2 ms-2\">\n");
      out.write("						<div class=\"title container d-flex mt-4\">\n");
      out.write("							<div class=\"title-bullet\"\n");
      out.write("								style=\"background-color: rgb(251, 201, 68);\"></div>\n");
      out.write("							<div id=\"title\">이용자층</div>\n");
      out.write("						</div>\n");
      out.write("						<ul class=\"people-group mt-2\">\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"age-10\" /> 10대\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li>\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"age-20\" /> 20대\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"age-30\" /> 30대\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"age-40\" /> 40대\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"age-50\" /> 50대\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"age-60\" /> 60대\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("						</ul>\n");
      out.write("						<ul class=\"gender-group d-flex mt-1\">\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"radio\" id=\"male\" name=\"gender\" />\n");
      out.write("										남성\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"radio\" id=\"female\" name=\"gender\" />\n");
      out.write("										여성\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("						</ul>\n");
      out.write("						<div class=\"hr col-9\">\n");
      out.write("							<hr />\n");
      out.write("						</div>\n");
      out.write("						<div class=\"title container d-flex mt-2\">\n");
      out.write("							<div class=\"title-bullet\"\n");
      out.write("								style=\"background-color: rgb(234, 99, 99);\"></div>\n");
      out.write("							<div id=\"title\">카테고리</div>\n");
      out.write("						</div>\n");
      out.write("						<ul class=\"category-group d-flex mt-2\">\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"cate-delivery\" />\n");
      out.write("										배달\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"cate-meal\" /> 밥집\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"cate-cafe\" /> 카페\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"cate-pub\" /> 술집\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"cate-gogi\" /> 고기\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"cate-seafood\" />\n");
      out.write("										횟집\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"cate-korean\" />\n");
      out.write("										한식\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"cate-china\" /> 중식\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"cate-japan\" /> 일식\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"cate-west\" /> 양식\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"cate-buffet\" />\n");
      out.write("										부페\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"cate-snack\" /> 분식\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("						</ul>\n");
      out.write("						<div class=\"hr col-9\">\n");
      out.write("							<hr />\n");
      out.write("						</div>\n");
      out.write("						<div class=\"title container d-flex mt-2\">\n");
      out.write("							<div class=\"title-bullet\"\n");
      out.write("								style=\"background-color: rgb(10, 199, 206);\"></div>\n");
      out.write("							<div id=\"title\">편의시설</div>\n");
      out.write("						</div>\n");
      out.write("						<ul class=\"convenience-group d-flex mt-2\">\n");
      out.write("							<li class=\"filter-button\">\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"conve-parking\" />\n");
      out.write("										주차\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("							<li>\n");
      out.write("								<div class=\"filter-button-click-container\">\n");
      out.write("									<label> <input type=\"checkbox\" id=\"conve-valet\" /> 발렛\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"map-body column-row col-10 ms-2\">\n");
      out.write("						<div class=\"map-main\" id=\"map\"></div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/mainPage/oneKmMap.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/mainPage/oneKmMap.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/mainPage/oneKmMap.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
