/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-17 12:46:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resources.images.reviews;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class a2311d64_002db51d_002d4492_002db403_002d54e5b3832889_005freview_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668700713831L));
    _jspx_dependants.put("jar:file:/C:/for%20studying/spring_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project_test/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <title>Jimat - Food choice for you</title>\r\n");
      out.write("    <link href=\"/css/review.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://kit.fontawesome.com/edd4d6d779.js\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"card p-3 col-lg-9 mt-3\" id=\"comment-body\">\r\n");
      out.write("      <div class=\"comment-box-body column-row p-3\">   \r\n");
      out.write("        <div class=\"comment-box column-row mb-4 column-row\">  \r\n");
      out.write("          <div class=\"row\" id=\"row1\">\r\n");
      out.write("          <div class=\"comment-rating d-flex justify-content-between p-0\">\r\n");
      out.write("            <div class=\"title m-0 p-0\">\r\n");
      out.write("              <p><h4>리뷰 작성하기</h4></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"rating flex-row-reverse ms-3\">\r\n");
      out.write("              <input type=\"radio\" name=\"rating\" value=\"1\" id=\"1\" />\r\n");
      out.write("              <label id=\"stars\" for=\"1\">☆</label>\r\n");
      out.write("              <input type=\"radio\" name=\"rating\" value=\"2\" id=\"2\" />\r\n");
      out.write("              <label id=\"stars\" for=\"2\">☆</label>\r\n");
      out.write("              <input type=\"radio\" name=\"rating\" value=\"3\" id=\"3\" />\r\n");
      out.write("              <label id=\"stars\" for=\"3\">☆</label>\r\n");
      out.write("              <input type=\"radio\" name=\"rating\" value=\"4\" id=\"4\" />\r\n");
      out.write("              <label id=\"stars\" for=\"4\">☆</label>\r\n");
      out.write("              <input type=\"radio\" name=\"rating\" value=\"5\" id=\"5\" />\r\n");
      out.write("              <label id=\"stars\" for=\"5\">☆</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"comment-tag\">\r\n");
      out.write("              <div\r\n");
      out.write("                class=\"btn-group\"\r\n");
      out.write("                role=\"group\"\r\n");
      out.write("                aria-label=\"Basic radio toggle button group\"\r\n");
      out.write("                >\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"checkbox\"\r\n");
      out.write("                    class=\"btn-check\"\r\n");
      out.write("                    name=\"btnradio\"\r\n");
      out.write("                    id=\"taste\"\r\n");
      out.write("                    autocomplete=\"off\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <label class=\"btn btn-outline-danger\" for=\"taste\">#맛</label>\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"checkbox\"\r\n");
      out.write("                    class=\"btn-check\"\r\n");
      out.write("                    name=\"btnradio\"\r\n");
      out.write("                    id=\"price\"\r\n");
      out.write("                    autocomplete=\"off\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <label class=\"btn btn-outline-warning\" for=\"price\">#가격</label>\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"checkbox\"\r\n");
      out.write("                    class=\"btn-check\"\r\n");
      out.write("                    name=\"btnradio\"\r\n");
      out.write("                    id=\"service\"\r\n");
      out.write("                    autocomplete=\"off\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <label class=\"btn btn-outline-info\" for=\"service\"\r\n");
      out.write("                    >#서비스</label\r\n");
      out.write("                  >\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"checkbox\"\r\n");
      out.write("                    class=\"btn-check\"\r\n");
      out.write("                    name=\"btnradio\"\r\n");
      out.write("                    id=\"mood\"\r\n");
      out.write("                    autocomplete=\"off\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <label class=\"btn btn-outline-primary\" for=\"mood\"\r\n");
      out.write("                    >#분위기</label\r\n");
      out.write("                  >\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"checkbox\"\r\n");
      out.write("                    class=\"btn-check\"\r\n");
      out.write("                    name=\"btnradio\"\r\n");
      out.write("                    id=\"parking\"\r\n");
      out.write("                    autocomplete=\"off\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <label class=\"btn btn-outline-success\" for=\"parking\"\r\n");
      out.write("                    >#주차</label\r\n");
      out.write("                  >\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("          <div class=\"row\" id=\"row2\">\r\n");
      out.write("            <div class=\"comment-area p-0\">\r\n");
      out.write("              <textarea\r\n");
      out.write("                class=\"form-control\"\r\n");
      out.write("                placeholder=\"리뷰를 입력해주세요\"\r\n");
      out.write("                rows=\"3\"\r\n");
      out.write("              ></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        <div class=\"row\" id=\"row3\">\r\n");
      out.write("          <div class=\"write-buttons mt-3 d-flex justify-content-center\">\r\n");
      out.write("            <input class=\"form-control\" type=\"file\" id=\"formFile\">  \r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" id=\"comment-send\">작성완료</button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("     \r\n");
      out.write("      <div class=\"card p-3 justify-content-start mt-2\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"card-title\">\r\n");
      out.write("            <h4>방문자 리뷰</h4>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"profile-body container\">\r\n");
      out.write("            <div class=\"comment-widgets d-flex m-b-20\">\r\n");
      out.write("              <div class=\"profile column-row mt-3\">\r\n");
      out.write("                <div class=\"profile-image\">\r\n");
      out.write("                  <span class=\"round\"\r\n");
      out.write("                    ><img\r\n");
      out.write("                      src=\"/data/images/profile1.png\"\r\n");
      out.write("                      alt=\"user\"\r\n");
      out.write("                      width=\"80\"\r\n");
      out.write("                      id=\"user_profile_image\"\r\n");
      out.write("                    />\r\n");
      out.write("                  </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"comment-options mt-3 d-flex justify-content-center\">\r\n");
      out.write("                  <div class=\"action-icons\">\r\n");
      out.write("                    <a href=\"#\" data-abc=\"true\" id=\"edit\"\r\n");
      out.write("                      ><i class=\"fa fa-pencil fa-lg\" id=\"edit\" alt=\"수정\" ></i\r\n");
      out.write("                    ></a></div>\r\n");
      out.write("                    <!-- 여기 하는 중 -->\r\n");
      out.write("                    \r\n");
      out.write("                  <div class=\"btn-group\" role=\"group\" aria-label=\"Basic checkbox toggle button group\" id=\"i-heart\">\r\n");
      out.write("                    <input\r\n");
      out.write("                      type=\"checkbox\"\r\n");
      out.write("                      class=\"btn-check\"\r\n");
      out.write("                      name=\"heart\"\r\n");
      out.write("                      id=\"i-heart\"\r\n");
      out.write("                      autocomplete=\"off\"/>\r\n");
      out.write("                      <label class=\"btn-outline-danger\" for=\"i-heart\">\r\n");
      out.write("                        <i class=\"fa fa-heart fa-lg\">         </i>                               </i>\r\n");
      out.write("                      </label>\r\n");
      out.write("                  </div>  \r\n");
      out.write("\r\n");
      out.write("                    <!-- -->\r\n");
      out.write("                  <p class=\"ms-1\">5</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"comment-inside p-3 col-2\">\r\n");
      out.write("                <div class=\"comment-info column-row\">\r\n");
      out.write("                  <div class=\"user_info\" id=\"user_nickname\">\r\n");
      out.write("                    <span id=\"user_nickname\"><h4>작성자 이름</h4></span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"user-rating d-flex\">\r\n");
      out.write("                    <div class=\"rating flex-row-reverse\">\r\n");
      out.write("                      <input\r\n");
      out.write("                        type=\"radio\"\r\n");
      out.write("                        name=\"rating\"\r\n");
      out.write("                        value=\"1\"\r\n");
      out.write("                        id=\"1\"\r\n");
      out.write("                      /><label for=\"1\">☆</label>\r\n");
      out.write("                      <input\r\n");
      out.write("                        type=\"radio\"\r\n");
      out.write("                        name=\"rating\"\r\n");
      out.write("                        value=\"2\"\r\n");
      out.write("                        id=\"2\"\r\n");
      out.write("                      /><label for=\"2\">☆</label>\r\n");
      out.write("                      <input\r\n");
      out.write("                        type=\"radio\"\r\n");
      out.write("                        name=\"rating\"\r\n");
      out.write("                        value=\"3\"\r\n");
      out.write("                        id=\"3\"\r\n");
      out.write("                      /><label for=\"3\">☆</label>\r\n");
      out.write("                      <input\r\n");
      out.write("                        type=\"radio\"\r\n");
      out.write("                        name=\"rating\"\r\n");
      out.write("                        value=\"4\"\r\n");
      out.write("                        id=\"4\"\r\n");
      out.write("                      /><label for=\"4\">☆</label>\r\n");
      out.write("                      <input\r\n");
      out.write("                        type=\"radio\"\r\n");
      out.write("                        name=\"rating\"\r\n");
      out.write("                        value=\"5\"\r\n");
      out.write("                        id=\"5\"\r\n");
      out.write("                      /><label for=\"5\">☆</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"write_date\">\r\n");
      out.write("                    <span class=\"date\" id=\"date\">April 14, 2019</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"comment-tag mt-1 container flex-wrap:wrap\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-danger\">맛</button>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-warning\">가격</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"comment-text mt-3\">\r\n");
      out.write("                <p id=\"comment-text\">\r\n");
      out.write("                  Lorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("                  typesetting industry. Lorem Ipsum has been the industry's\r\n");
      out.write("                  standard dummy text ever since the 1500s, when an unknown\r\n");
      out.write("                  printer took a galley of type and scrambled it\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"container d-flex p-3\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"review-images col-3\">\r\n");
      out.write("                    <img src=\"/data/images/review_images1.jpg\" />\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"review-images col-3\">\r\n");
      out.write("                    <img src=\"/data/images/review_images2.jpg\" />\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"review-images col-3\">\r\n");
      out.write("                    <img src=\"/data/images/review_images3.jpg\" />\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"review-images col-3\">\r\n");
      out.write("                    <img src=\"/data/images/review_images4.jpg\" />\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
